#!/bin/bash

source /etc/admin-tools.settings.cfg
source /var/domains/tools/common.sh
check_user

if [ -z "$1" ]
    then
    echo_failure "No SiteName"
    exit 1
fi
if [ -z "$2" ]
    then
    echo_failure "No Redirect URL"
    exit 1
fi

site_name=$1
redirection=$2

echo "Generating $site_name:"
echo -n "   - Apache config: "

rm -rf /var/domains/confs/$site_name &> /dev/null
cat >> /var/domains/confs/$site_name << EOF
<VirtualHost *:80>
        ServerAdmin $ADMINTOOLS_DEFAULT_SERVER_ADMIN
        ServerName  $site_name
        ServerAlias www.$site_name

        ProxyRequests off

        <Proxy *>
                Order deny,allow
                Allow from all
        </Proxy>

        <Location />
                ProxyPass $redirection
                ProxyPassReverse $redirection
        </Location>
</VirtualHost>
EOF
ln -s /var/domains/confs/$site_name /etc/apache2/sites-available/$site_name &>/dev/null

echo_success

echo -n "   - Enabling Apache modules: "
a2enmod proxy >> /dev/null
a2enmod proxy_http >> /dev/null

echo_success

echo -n "   - Enabling Apache domain: "
a2ensite $site_name >> /dev/null
echo_success

echo ""
echo "Reload apache to enable the domain with this command:"
echo "   service apache2 reload"

