#!/bin/bash

source /etc/admin-tools.settings.cfg
source /var/domains/tools/common.sh
check_user

service apache2 stop
service mysql restart
mkdir -p /var/domains/backups/$(date +%Y%m%d)/
sleep 5
mysqldump -u $ADMINTOOLS_MYSQL_ROOT_ACCOUNT -p"$ADMINTOOLS_MYSQL_PASSWORD" --all-databases | gzip > /var/domains/backups/$(date +%Y%m%d)/databases.sql.gz
tar -cvpjf /var/domains/backups/$(date +%Y%m%d)/files.tar.bz2 /var/domains --exclude=*.log --exclude=*.pyc --exclude=/var/domains/backups
service apache2 restart

transmission-create /var/domains/backups/$(date +%Y%m%d)/ -t "udp://tracker.openbittorrent.com:80" -t "udp://tracker.publicbt.com:80/announce" -o /var/domains/backups/torrents/$(date +%Y%m%d).torrent 