#!/bin/bash

source /etc/admin-tools.settings.cfg
source /var/domains/tools/common.sh

if [ -z "$1" ]
    then
    echo_failure "No SiteName given"
    exit 1
fi

if [ -z "$2" ]
    then
    echo_failure "No WSGI path given"
    exit 1
fi


if [ -z "$3" ]
    then
    echo_failure "No username (The user that will run the wsgi script)  given"
    exit 1
fi

site_name=$1
wsgi_path=$2
username_to_use=$3

echo "Generating $site_name:"
echo -n "   - Apache config: "

rm -rf /var/domains/confs/$site_name &> /dev/null
cat >> /var/domains/confs/$site_name << EOF
<VirtualHost *:80>
        ServerAdmin $ADMINTOOLS_DEFAULT_SERVER_ADMIN
        ServerName  $site_name
        ServerAlias www.$site_name

        WSGIDaemonProcess $username_to_use user=$username_to_use group=$username_to_use threads=5
        WSGIScriptAlias / $wsgi_path
    
        <Directory /var/domains/sites/$site_name>
            WSGIProcessGroup $username_to_use
            WSGIApplicationGroup %{GLOBAL}
            Order deny,allow
            Allow from all
        </Directory>
    
        # Logfiles
        ErrorLog  /var/domains/sites/$site_name/logs/error.log
        CustomLog /var/domains/sites/$site_name/logs/access.log combined
</VirtualHost>
EOF

ln -s /var/domains/confs/$site_name /etc/apache2/sites-available/$site_name &>/dev/null
echo_success

echo -n "   - Enabling Apache domain: "
a2ensite $site_name >> /dev/null
echo_success

echo ""
echo "Reload apache to enable the domain with this command:"
echo "   service apache2 reload"

