#!/bin/bash

source /etc/admin-tools.settings.cfg
source /var/domains/tools/common.sh
check_user

if [ -z "$1" ]
    then
    echo_failure "No SiteName"
    exit 1
fi
site_name=$1

echo "Deleting $site_name:"
echo -n "   - Disabling Apache config: "

a2dissite $site_name >> /dev/null
service apache2 reload &> /dev/null

echo_success

echo -n "   - Deleting Apache config: "

rm -rf /var/domains/confs/$site_name &> /dev/null
rm /etc/apache2/sites-available/$site_name &>/dev/null

echo_success
