#!/bin/bash
if [ -z "$1" ]
    then
    echo "No SiteName"
    exit 1
fi
site_name=$1

echo "Deleting $site_name:"
echo -n "   - Disabling Apache config: "

sudo a2dissite $site_name >> /dev/null
sudo service apache2 reload &> /dev/null

echo "done"

echo -n "   - Deleting Apache config: "

sudo rm -rf /var/domains/confs/$site_name &> /dev/null
sudo rm /etc/apache2/sites-available/$site_name &>/dev/null

echo "done"
