#!/bin/bash
if [ -z "$1" ]
    then
    echo "No SiteName"
    exit 1
fi
if [ -z "$2" ]
    then
    echo "No Redirect URL"
    exit 1
fi

site_name=$1
redirection=$2

echo "Generating $site_name:"
echo -n "   - Apache config: "

sudo rm -rf /var/domains/confs/$site_name &> /dev/null
sudo cat >> /var/domains/confs/$site_name << EOF
<VirtualHost *:80>
        ServerAdmin koalalorenzo@gmail.com
        ServerName  $site_name
        ServerAlias www.$site_name

        Redirect permanent / $redirection
</VirtualHost>
EOF
sudo ln -s /var/domains/confs/$site_name /etc/apache2/sites-available/$site_name &>/dev/null
echo "done"

echo -n "   - Enabling Apache domain: "
sudo a2ensite $site_name >> /dev/null
echo "done"
echo ""
echo "Reload apache to enable the domain with this command:"
echo "   sudo service apache2 reload"

