#!/bin/bash

source /etc/admin-tools.settings.cfg
source /var/domains/tools/common.sh

if [ -z "$1" ]
    then
    echo "No argument supplied"
    exit 1
fi

site_name=$1
echo "Generating $site_name:"
echo -n "   - Apache config: "

sudo rm -rf /var/domains/confs/$site_name &> /dev/null
sudo cat >> /var/domains/confs/$site_name << EOF
<VirtualHost *:80>
    ServerAdmin $ADMINTOOLS_DEFAULT_SERVER_ADMIN
    ServerName  $site_name
    ServerAlias www.$site_name

    #        DocumentRoot /var/domains/sites/$site_name/
    #        Alias /icons /var/domains/sites/$site_name/www/icons

    # Logfiles
    ErrorLog  /var/domains/sites/$site_name/logs/error.log
    CustomLog /var/domains/sites/$site_name/logs/access.log combined
    WSGIScriptAlias / /var/domains/sites/$site_name/hgweb.wsgi
    <Location />
        AuthType Basic
        AuthName "Mercurial repositories"
        AuthUserFile /var/domains/sites/$site_name/hgusers
        Require valid-user
    </Location>
</VirtualHost>  
EOF
sudo ln -s /var/domains/confs/$site_name /etc/apache2/sites-available/$site_name &>/dev/null
echo "done"

echo -n "   - Default files structure: "
sudo mkdir -p /var/domains/sites/$site_name/www /var/domains/sites/$site_name/logs &>/dev/null
echo "done"

echo -n "   - Creating Repositories structure: "
sudo cat >> /var/domains/sites/$site_name/hgweb.config << EOF
[collections]
/var/domains/sites/$site_name/www = /var/domains/sites/$site_name/www

[web]
allow_push = $ADMINTOOLS_MERCURIAL_USERNAME
push_ssl = false
EOF

sudo cat >> /var/domains/sites/$site_name/hgweb.wsgi << EOF
from mercurial.hgweb.hgweb_mod import hgweb
from mercurial.hgweb.hgwebdir_mod import hgwebdir

CONFIG = '/var/domains/sites/$site_name/hgweb.conf'
application = hgwebdir(CONFIG)
EOF
echo "done"

echo -n "   - Changing files owner: "
sudo chown -R www-data:www-data /var/domains/sites/$site_name &> /dev/null
echo "done"

echo -n "   - Enabling Apache domain: "
sudo a2ensite $site_name >> /dev/null
echo "done"
echo ""
echo "Reload apache to enable the domain with this command:"
echo "   sudo service apache2 reload"
echo "Set users permissions with this command in /var/domains/sites/$site_name:"
echo "   htpasswd -mc hgusers admin"
