#!/bin/bash

source /etc/admin-tools.settings.cfg
source /var/domains/tools/common.sh

if [ -z "$1" ]
    then
    echo_failure "No site name supplied"
    exit 1
fi

site_name=$1
echo "Generating $site_name:"
echo -n "   - Apache config: "

rm -rf /var/domains/confs/$site_name &> /dev/null
cat >> /var/domains/confs/$site_name << EOF
<VirtualHost *:80>
        ServerAdmin $ADMINTOOLS_DEFAULT_SERVER_ADMIN
        ServerName  $site_name
        ServerAlias www.$site_name

        DocumentRoot /var/domains/sites/$site_name/www/
        Alias /icons /var/domains/sites/$site_name/www/icons

        # Logfiles
        ErrorLog  /var/domains/sites/$site_name/logs/error.log
        CustomLog /var/domains/sites/$site_name/logs/access.log combined
</VirtualHost>
EOF
ln -s /var/domains/confs/$site_name /etc/apache2/sites-available/$site_name &>/dev/null
echo_success

echo -n "   - Default files structure: "
mkdir -p /var/domains/sites/$site_name/www /var/domains/sites/$site_name/logs &>/dev/null
echo_success

echo -n "   - Changing files owner: "
chown -R www-data:www-data /var/domains/sites/$site_name &> /dev/null
echo_success

echo -n "   - Enabling Apache domain: "
a2ensite $site_name >> /dev/null
echo_success

echo ""
echo "Reload apache to enable the domain with this command:"
echo "   service apache2 reload"

